### ISSUE TITLE
Formating GWAS summarys tatistics function giving a sed command error

### ISSUE THREAD

**Issue by deevdevil88** [neurogenomics/MAGMA_Celltyping#1]
Hello,
I have been trying to use your package. I have been getting a sed command error while tyring to format my GWAS summary statistics files using your function. I wondered if the sed -i command was coded for MAC OS versions of sed rather than linux GNU sed?

Is it possible to get an alternative fix? as evethough it corrects some formatting bits, but not everything, I get an error while running MAGMA after.

Thanks
Devika

**Comment by rbutleriii** [comment]
Hello, having the same issue running in ubuntu 18.04. I saw there are a couple of "crossplatform" scripts , `standardise.sumstats.column.headers.crossplatform.R` and `format_sumstats_for_magma_crossplatform.R` that were added recently but have not been integrated with the package. I copied them and gave them a go, with the tutorial dataset: `20016.assoc.tsv`

As written still some bugs, but I am not adept at R scripting. I did fix the first issue I encountered: when `VARIANT` is changed out for `CHR\tBP\tA1\tA2`, it replaces the header row entirely. Instead, this works in `format_sumstats_for_magma_crossplatform.R` at line 105:
```
    # Check if there is a column of data with CHR:BP:A2:A1 format
    fourStepCol = grep(".*:.*:\\w:\\w",row_of_data)
    if(length(fourStepCol)){
      # Convert the ':' into '\t'
      sumstats_file <- gsub(pattern = ":", replace = "\t", x = sumstats_file)
      # Replace the column name with four names
      curColName = strsplit(col_headers, "\t")[[1]][fourStepCol]
      new_first_line = gsub(curColName, "CHR\tBP\tA2\tA1", col_headers)
      # Write the new column headers to file
      sumstats_file[1] = new_first_line
      print(sprintf("Column %s has been replaced with CHR BP A2 A1", curColName))
      col_headers = strsplit(new_first_line, "\t")[[1]]
      print(col_headers)
      row_of_data <- strsplit(sumstats_file[2], "\t")[[1]]
      print(row_of_data)
```
However, the next bug encountered is:
```
> col_headers = format_sumstats_for_magma_crossplatform(gwas_sumstats_path)
[1] "First line of summary statistics file: "
[1] "variant\trsid\tnCompleteSamples\tAC\tytx\tbeta\tse\ttstat\tpval"
[1] "variant"          "rsid"             "nCompleteSamples" "AC"               "ytx"              "beta"             "se"              
[8] "tstat"            "pval"            
[1] "VARIANT"          "RSID"             "NCOMPLETESAMPLES" "AC"               "YTX"              "BETA"             "SE"              
[8] "TSTAT"            "PVAL"            
[1] "Summary statistics file does not have obvious CHR or BP columns. Checking to see if they are joined in another column"
[1] "Column VARIANT has been replaced with CHR BP A2 A1"
 [1] "CHR"   "BP"    "A2"    "A1"    "SNP"   "N"     "AC"    "YTX"   "BETA"  "SE"    "TSTAT" "P"    
 [1] "5"           "43888254"    "C"           "T"           "rs13184706"  "108818"      "3.90986e+03" "2.43293e+04" "3.97607e-02"
[10] "3.41292e-02" "1.16501e+00" "2.44019e-01"
[1] "First line of summary statistics file: "
[1] "CHR\tBP\tA2\tA1\tSNP\tN\tAC\tYTX\tBETA\tSE\tTSTAT\tP"
 [1] "CHR"   "BP"    "A2"    "A1"    "SNP"   "N"     "AC"    "YTX"   "BETA"  "SE"    "TSTAT" "P"    
 [1] "CHR"   "BP"    "A2"    "A1"    "SNP"   "N"     "AC"    "YTX"   "BETA"  "SE"    "TSTAT" "P"    
[1] "Checking that there is at least one signed sumstats column (eg.: Z, OR, BETA, LOG_ODDS, SIGNED_SUMSTAT)"
[1] "Checking that the first three column headers are SNP, CHR and BP in this order."
 Hide Traceback
 
 Rerun with Debug
 Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 2118 did not have 12 elements 
5.
scan(file = file, what = what, sep = sep, quote = quote, dec = dec, 
    nmax = nrows, skip = 0, na.strings = na.strings, quiet = TRUE, 
    fill = fill, strip.white = strip.white, blank.lines.skip = blank.lines.skip, 
    multi.line = FALSE, comment.char = comment.char, allowEscapes = allowEscapes,  ... 
4.
read.table(path) 
3.
is.data.frame(x) 
2.
write.table(x = read.table(path)[, c(whichSNP, whichCHR, whichBP, 
    otherCols)], file = path, sep = "\t", quote = FALSE, row.names = FALSE, 
    col.names = FALSE) 
1.
format_sumstats_for_magma_crossplatform(gwas_sumstats_path) 
```

**Comment by rbutleriii** [comment]
Update: line 2118 had chr:pos in lieu of an rsid in the SNP column. This version works and moves on to next sections, but now appears to hang on the low Pvalue prompt (or at least has been running for 8 hours):
```
    # Check if there is a column of data with CHR:BP:A2:A1 format
    fourStepCol = grep(".*:.*:\\w:\\w",row_of_data)
    if(length(fourStepCol)){
      # Convert the ':' into '\t', avoiding SNP column with chr:pos in place of missing rs
      sumstats_file <- gsub(pattern = "(\\w+):(\\d+):(\\w+):(\\w+)", replace = "\\1\t\\2\t\\3\t\\4", perl = TRUE, x = sumstats_file)
      # Replace the column name with four names
      curColName = strsplit(col_headers, "\t")[[1]][fourStepCol]
      new_first_line = gsub(curColName, "CHR\tBP\tA2\tA1", col_headers)
      # Write the new column headers to file
      sumstats_file[1] = new_first_line
      print(sprintf("Column %s has been replaced with CHR BP A2 A1", curColName))
      col_headers = strsplit(new_first_line, "\t")[[1]]
      print(col_headers)
      row_of_data <- strsplit(sumstats_file[2], "\t")[[1]]
      print(row_of_data)
    }
```

**Comment by rbutleriii** [comment]
Finished with warnings:
```
> col_headers = format_sumstats_for_magma_crossplatform(gwas_sumstats_path)
[1] "First line of summary statistics file: "
[1] "variant\trsid\tnCompleteSamples\tAC\tytx\tbeta\tse\ttstat\tpval"
[1] "variant"          "rsid"             "nCompleteSamples" "AC"               "ytx"              "beta"             "se"              
[8] "tstat"            "pval"            
[1] "VARIANT"          "RSID"             "NCOMPLETESAMPLES" "AC"               "YTX"              "BETA"             "SE"              
[8] "TSTAT"            "PVAL"            
[1] "Summary statistics file does not have obvious CHR or BP columns. Checking to see if they are joined in another column"
[1] "Column VARIANT has been replaced with CHR BP A2 A1"
 [1] "CHR"   "BP"    "A2"    "A1"    "SNP"   "N"     "AC"    "YTX"   "BETA"  "SE"    "TSTAT" "P"    
 [1] "5"           "43888254"    "C"           "T"           "rs13184706"  "108818"      "3.90986e+03" "2.43293e+04" "3.97607e-02"
[10] "3.41292e-02" "1.16501e+00" "2.44019e-01"
[1] "First line of summary statistics file: "
[1] "CHR\tBP\tA2\tA1\tSNP\tN\tAC\tYTX\tBETA\tSE\tTSTAT\tP"
 [1] "CHR"   "BP"    "A2"    "A1"    "SNP"   "N"     "AC"    "YTX"   "BETA"  "SE"    "TSTAT" "P"    
 [1] "CHR"   "BP"    "A2"    "A1"    "SNP"   "N"     "AC"    "YTX"   "BETA"  "SE"    "TSTAT" "P"    
[1] "Checking that there is at least one signed sumstats column (eg.: Z, OR, BETA, LOG_ODDS, SIGNED_SUMSTAT)"
[1] "Checking that the first three column headers are SNP, CHR and BP in this order."
 [1] "CHR"   "BP"    "A2"    "A1"    "SNP"   "N"     "AC"    "YTX"   "BETA"  "SE"    "TSTAT" "P"    
[1] "Removing duplicated columns (if any)."
MAGMA cannot handle P-values as low as 3e-400. Do you want MAGMA.celltyping to convert any (if) existing ones to zeroes? 0 for NO, 1 for YES\nTRUE
Sometimes the N column is not all integers. Do you want MAGMA.celltyping to (if such instances exist) round them up? 0 for NO, 1 for YESTRUE
[1] "Dropping all rows that don't start with 'rs'"
[1] "Keeping only rows which have the number of columns expected."
[1] "Removing duplicated RSIDs."
[1] "Succesfully finished preparing sumstats file:"
[1] "Header of file:"
[1] "SNP\tCHR\tBP\tA2\tA1\tN\tAC\tYTX\tBETA\tSE\tTSTAT\tP"                                                      
[2] "rs13184706\t5\t43888254\tC\tT\t108818\t3.90986e+03\t2.43293e+04\t3.97607e-02\t3.41292e-02\t1.16501e+00\tNA"
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In `[<-.factor`(`*tmp*`, iseq, value = 0.244019) :
  invalid factor level, NA generated
2: In `[<-.factor`(`*tmp*`, iseq, value = 0.887858) :
  invalid factor level, NA generated
```
Written to a tmp dir, but the Pvalue step produced NAs (hence the warnings). Also the rounding N step produced all `108818`. I think that is a data class thing. 

Unrelated: 
- logical prompts require TRUE/FALSE, 1/0 cause error.

- In the tutorial, `col_headers` is not used in subsequent commands, but is the path to the modified file

**Comment by rbutleriii** [comment]
Actually, I am being silly by rewriting the whole thing. The only problem here is that GNU sed is `sed -i '1s/old/new' file/path` and BSD sed is `sed -i '' '1s/old/new' file/path`. So I forked the repo and there created a new R script to cope with linux stat file formatting `format_sumstats_for_magma_linux()`. Additionally, it addresses issue #5 .

Alternately, this could be fixed by replacing `sed` with `perl`, as `perl -i -pe '1s/old/new' file/path` is the same for both (and potentially windows), but perhaps the totally cross-platform script using R functions would be easiest.

**Comment by NathanSkene** [comment]
Hi Rob,

Do you think your version of the crossplatform function would be an improvement over the existing one? Happy to pull it into the repository if so. I've not really done any testing of the crossplatform versions, but have had a few other emailed queries about it.

**Comment by rbutleriii** [comment]
`format_sumstats_for_magma_linux.r` seems to work on linux, with the prerequisite of gawk in-place [functionality](https://stackoverflow.com/questions/16529716/awk-save-modifications-in-place) (>v4.1). I assumed that would be broadly adopted by now, but apparently not in CentOS7 and perhaps other linux distros? With the right gawk, I still got an error on one of the GWAS sets I tried, but seemed to correctly finish anyways. I tried PGC SCZ2, Jansen AD, Alkes Price Lab versions of UKBB BMIz and Heightz, Nalls et al 2019 PD w/o 23andMe. 

However, `format_sumstats_for_magma_linux.r` won't work on Windows, so in that sense the cross-platform version currently in development `format_sumstats_for_magma_crossplatform.r` would be better in that it is purely R. My version is more like a band aid than an improvement. I just ran into several issues, and I am not a strong enough R programmer to debug them. 

I think where I left the crossplatform verison above, the `108818` was correct, that is the sample size, and the col_headers thing was also correct, I just didn't understand how the script worked downstream. It runs into issues on GWAS sets where `chr:pos` is used in place of rs numbers in the `SNP` column (Jansen_AD I think). Having the inconsistent number of columns for those rows halts the `read.table()` function for the `convert low P-val -> 0` and the `round Ns` sections. In my linux version I added a workaround that might help with that, a true/false variable that checks if the `fourStepCol` loop has already run before running the `twoStepCol` loop:
```
        four_colon_col = NULL
        
        # Check if there is a column of data with CHR:BP:A2:A1 format
        fourStepCol = grep(".*:.*:\\w:\\w",row_of_data)
        print("CHR:BP:A1:A2 column found, splitting...")
        if(length(fourStepCol)){
        .
        .
        .
            # Add a skip condition to twoStepCol below
            four_colon_col = TRUE
        }
        
        # Check if there is a column of data with CHR:BP format
        twoStepCol = grep(".*:.*",row_of_data)
        print("CHR:BP column found, splitting...")
        if(length(twoStepCol) & !isTRUE(four_colon_col)){

```
If there is a GWAS set that has `chr:pos` twice in a row, I am not sure there is a good solution. Also seems pretty unlikely. The other things to fix for the crossplatform verison were minor. The logical conditional prompts required `TRUE/FALSE`, not `1/0`. Although the script usually takes a while to run, with the prompts occurring some time after the script started.  Those prompts could just be removed and have the Pvalue and N conversions by default, as in the original script. 

Lastly, `format_sumstats_for_magma_crossplatform.r` and `standardise.sumstats.column.headers.crossplatform.r` are not added to `NAMESPACE` yet.

**Comment by alexandruioanvoda** [comment]
Hi @rbutleriii & @NathanSkene ,

The cross platform version I pulled back in November was accidentally an early version (with code that doesn't work) instead of the working one. I'll update my fork to the current version of @NathanSkene 's code, and add the functioning R code. My deepest apologies.

Please try it out (will add github link here in 20 mins, this is the temporary pastebin: https://pastebin.com/vrvLbi1c) and let me know if it works for you too (I tested it on the `20016.assoc.tsv` and another published sumstats file).

That being said, it is sort of too slow in pure R (which is the reason why Dr. N. Skene didn't put an R version here initially).

Is there a way to include a sort of Conda/virtualenv environment that contains the correct awk/gawk/sed versions inside, that can be shipped with the R package and called from inside? That would be both quick and portable enough among UNIX-based OSes.

**Or Perl!** A Perl version would be great!

Anyhow, sumstats can and unfortunately are uploaded in countless formats online, so it is practically hard to write a function to correctly convert any to the desired format.

Therefore, I guess another way to do this would be to upload a small (e.g. 20 row) example sumstat with all the **essential columns** (e.g. `c("SNP","CHR","BP","P","A1","A2")` & at least one of the `c("Z","OR","BETA","LOG_ODDS","SIGNED_SUMSTAT")`), tab-spaced, and ask all users to format their sumstats just like the example.

**Comment by NathanSkene** [comment]
That would be great, thanks Alex

It is pretty frustrating that the community can't just agree on a common set of column names

I'll add the notes about columns & a test dataset into the tutorial. Should have thought of that before!

**Comment by alexandruioanvoda** [comment]
> TSV file (FS="\t") containing the following columns and header: { SNP (rs id), CHR, BP (basepair) (first 3 in this order!), P (P-value), A1 (effect allele), A2 (non-effect allele), at least one signed sumstats column from {Z, OR, BETA, LOG_ODDS, SIGNED_SUMSTAT}}
> 
> Practical example:
> 
> SNP	CHR	BP	A1	A2	P	BETA
> rs9296934	6	9682090	G	A	9.66706e-01	-3.77321e-04
> rs190875039	6	9682484	C	A	2.82439e-02	-2.17522e-01
> rs182100404	6	9682485	C	A	2.85886e-02	-2.16271e-01

Promise to upload the working R version in the morning

**Comment by alexandruioanvoda** [comment]
Hi! The working R versions are here: https://github.com/alexandruioanvoda/MAGMA_Celltyping-1/blob/master/R/standardise.sumstats.column.headers.r (same as the old)
https://github.com/alexandruioanvoda/MAGMA_Celltyping-1/blob/master/R/format_sumstats_for_magma_crossplatform.r (the changed one)

For speed purposes, I checked them right now with a subset made with `head -n 10000 20016.assoc.tsv > 20016.subsamp.assoc.tsv` and ran `format_sumstats_for_magma_crossplatform("20016.subsamp.assoc.tsv")`

and got this:

> [1] "Copying into intermediary file (in order to not modify the original)."
> [1] "Loading sumstats file."
> [1] "Ensuring that FS are tabs, not spaces."
> [1] "This GWAS sumstat file has 'space' FS instead of tabs (unusual, not proper input for MAGMA). Correcting in output file."
> [1] "First line of summary statistics file: "
> [1] "variant\trsid\tnCompleteSamples\tAC\tytx\tbeta\tse\ttstat\tpval"
> [1] "variant"          "rsid"             "nCompleteSamples" "AC"               "ytx"              "beta"            
> [7] "se"               "tstat"            "pval"            
> [1] "VARIANT"          "RSID"             "NCOMPLETESAMPLES" "AC"               "YTX"              "BETA"            
> [7] "SE"               "TSTAT"            "PVAL"            
> [1] "Summary statistics file does not have obvious CHR or BP columns. Checking to see if they are joined in another column"
> [1] "Column VARIANT is being replaced with CHR BP A2 A1"
> [1] "First line of summary statistics file: "
> [1] "CHR\tBP\tA2\tA1\tSNP\tN\tAC\tYTX\tBETA\tSE\tTSTAT\tP"
>  [1] "CHR"   "BP"    "A2"    "A1"    "SNP"   "N"     "AC"    "YTX"   "BETA"  "SE"    "TSTAT" "P"    
>  [1] "CHR"   "BP"    "A2"    "A1"    "SNP"   "N"     "AC"    "YTX"   "BETA"  "SE"    "TSTAT" "P"    
> [1] "Eliminating any rows (SNPs) that have more columns than the header. Current number of rows: 10000"
> [1] "Rows left after processing: 10000"
> [1] "Checking that all the vital columns are present (SNP, CHR, BP, P, A1, A2)."
> [1] "Checking that there is at least one signed sumstats column (eg.: Z, OR, BETA, LOG_ODDS, SIGNED_SUMSTAT)"
> [1] "All vital columns present."
> [1] "Checking that the first three column headers are SNP, CHR and BP in this order."
> [1] "Reordering the columns (to be SNP, CHR and BP et al.). This may take 30 seconds - 15 mins depending on hardware and sumstats file size."
> [1] "The following operation may take 30 seconds - 15 minutes depending on hardware and sumstats file size."
> [1] "MAGMA cannot handle P-values as low as 3e-400."
> Do you want MAGMA.celltyping to convert any (if) existing ones to zeroes? [ y/n ]: y
> [1] "The following operation may take 30 seconds - 15 minutes depending on hardware and sumstats file size."
> [1] "Sometimes the N column is not all integers."
> Do you want MAGMA.celltyping to round them up if existing? [ y/n ]: y
> [1] "Dropping all rows that don't start with 'rs'"
> [1] "Removing duplicated RSIDs."
> [1] "Succesfully finished preparing sumstats file:"
> [1] "Header of file:"
> [1] "SNP\tCHR\tBP\tA2\tA1\tN\tAC\tYTX\tBETA\tSE\tTSTAT\tP"                                                            
> [2] "rs13184706\t5\t43888254\tC\tT\t108818\t3.90986e+03\t2.43293e+04\t3.97607e-02\t3.41292e-02\t1.16501e+00\t0.244019"
>  [1] "SNP"   "CHR"   "BP"    "A2"    "A1"    "N"     "AC"    "YTX"   "BETA"  "SE"    "TSTAT" "P"    
> [1] "/gfs/work/avoda/ibd/Scripts/MAGMA_sumstats_munger/20016.subsamp.assoc.tsv_processed.sumstats"

And the file looks just fine.

The headers of the functions have changed for ROxygen2, so I guess they would only require ROxygen2 to run again on the project in order to be added to the NAMESPACE.

**Comment by rbutleriii** [comment]
Well I probably should have found this sooner, but:
https://stackoverflow.com/a/22084103/8034603
so potentially the sed commands in the standard version can be modified to run on BSD and GNU systems.

**Comment by rbutleriii** [comment]
In my fork I put a `test` folder that contains a zipped set of gwas file `head`'s (first 100k lines), a `test.R` script and a `command` executable that will unzip the files, test them in both the crossplatform and linux versions and generate `results.txt` files. I updated my fork's crossplatform script to be Alex's newest version, with the input options commented out an set to specify GRCh37, yes to N rounding and yes to Pvalue zeroing by default. I updated my fork's linux version to use `sed -i.bak` as in the stackoverflow example, and it runs on BSD sed. Initial timing with 50k lines was 13 seconds for all six GWAS linux, 2:35 crossplatform. 

From the results, neither succeeded all the time, but linux almost did. It failed on CLOZUK_SCZ, where it  successfully looked up the missing rs numbers, but failed to remove the original SNP field before inserting the new rs. The crossplatform didn't reorder the columns for CLOZUK, IGAP or PGC_SCZ2, and didn't look up rs numbers for CLOZUK, but otherwise seems to have completed. (all of them in both cases said successfully run).

If they both end up producing the same output, the linux version could replace the standard version as the impatient form, and the crossplatform would be useful for a truly crossplatform for those who have windows, or other compatibility issues.

Of general consequence: IGAP has a heading `hg19chrc` for its `CHR` column that is a pain, and Jansen AD set has an annoying header issue where there are spaces instead of a tab in only one column gap: between  `BP` and `A1` which is not filtered by the header checker (resulting in a `BP       A1` column). I have seen it in the sumstats from multiple sources, so I think it is from the original.

**Comment by alexandruioanvoda** [comment]
> Well I probably should have found this sooner, but:
> https://stackoverflow.com/a/22084103/8034603
> so potentially the sed commands in the standard version can be modified to run on BSD and GNU systems.

Although the most portable version is really just `sed 'script' tmp && mv tmp file`, and the `-infile` argument does the same thing with no speed gain. Source: https://stackoverflow.com/a/5174368 and https://stackoverflow.com/a/41994244

Thanks for the tests @rbutleriii ! Will look into the `CLOZUK, IGAP or PGC_SCZ2` issues later today!

**Comment by rbutleriii** [comment]
True, it is not a speed difference with the seds, but adding the -i.bak component tricks Gnu sed into cooperating with the same script as BSD sed. I also ran the test on Ubuntu 18.04LTS this morning with identical results. Worth noting that ubuntu doesn't ship with gawk, so maybe mention as prereq.
