### ISSUE TITLE
MAGMA_Files_Public studies identification

### ISSUE THREAD

**Issue by sofiapuvogelvittini** [neurogenomics/MAGMA_Celltyping#103]
Hello, 
Thanks for the very nice package.
I am having trouble identifying the authors and original paper of some studies in 
https://github.com/neurogenomics/MAGMA_Files_Public/blob/master/metadata.csv

Could you help me to identify the original paper of **finn-a-PDSTRICT**?
Thanks a lot

**Comment by bschilder** [comment]
Hi @sofiapuvogelvittini , the PubMed ID should be under the "pmid" column. If it's empty or NA, I'm afraid that's something you would have to reach out to the [Open GWAS ](https://gwas.mrcieu.ac.uk/)team or [FinnGenn](https://www.finngen.fi/en/access_results) team about, because that's where the data/metadata ultimately comes from.
