### ISSUE TITLE
get_ctd doesn't work - "missing token error"

### ISSUE THREAD

**Issue by the-confused-scientist** [neurogenomics/MAGMA_Celltyping#140]
## 1. Bug description

when I try to get the allAIBS or DRONC datasets for my cell type dataset I can base the enrichment on, it errors and tells me I am missing a token and need to configure git with R - I reinstalled git and now I get the error you see below:

### Console output 

```
# Paste console output here (from R)
Error in `value[[3L]]()`:
! Cannot access release data for repo "neurogenomics/MAGMA_Celltyping".
Check that you have provided a `.token` and that the repo is correctly
specified.
GitHub API error (401): Bad credentials

```

### Expected behaviour   

I assume it should download from the github repo the cell type dataset that I want to use?

### Code 

(Please add the steps to reproduce the bug here. See [here](https://www.r-bloggers.com/2020/10/how-to-make-a-reprex/) for an intro to making a reproducible example (i.e. reprex) and why they're important! __This will help us to help you much faster.__)

```R
# Paste example here
ctd <- get_ctd("ctd_allAIBS") #for example
```

### Data

(If possible, upload a small sample of your data so that we can reproduce the bug on our end. If that's not possible, please at least include a screenshot of your data and other relevant details.)

## 3. Session info

(Add output of the R function `utils::sessionInfo()` below. This helps us assess version/OS conflicts which could be causing bugs.)

<details>

```
# Paste utils::sessionInfo() output 

```
</details>

**Comment by bschilder** [comment]
You need to follow the instructions in the error message and provide a GitHub token.
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

Lots of way to do this, but the easiest is to add it as an environmental variable in your `~/.Renviron file`. That it will automatically be loaded into the environment every time you open a new R session.


This is so that the function can download the data from GitHub Releases via `piggyback`:
https://github.com/ropensci/piggyback
