### ISSUE TITLE
Does MAGMA_Celltyping regenerate quantiles, even when EWCE has already generated them, and then save them to a new location?

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/MAGMA_Celltyping#36]
@bschilder mentioned that this happened: can you write some notes here on what happens?

**Comment by bschilder** [comment]
## EWCE 

Generates specificity quantiles using the `EWCE::bin.specificity.into.quantiles()` function, and stores it in the `specificity_quantiles` slot. 

![Screenshot 2021-05-11 at 12 09 38](https://user-images.githubusercontent.com/34280215/117806130-cad53e80-b251-11eb-8850-f226379a6c4a.png)


## MAGMA_Celltyping 

Generates specificity quantiles using the `MAGMA.Celltyping::prepare.quantile.groups()` function, and stores it in the `specDist_quantiles` slot. Because of the different naming schemes, specificity and quantiles are recomputed even when `specificity` and `specificity_quantiles` were already calculated via EWCE.

![Screenshot 2021-05-11 at 12 12 21](https://user-images.githubusercontent.com/34280215/117806406-3a4b2e00-b252-11eb-8363-dfc245828011.png)

**Comment by NathanSkene** [comment]
Thanks!
