### ISSUE TITLE
Check how automated install options for magma behave on various operating systems & HPC & Travis & GithubActions

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/MAGMA_Celltyping#49]

**Comment by bschilder** [comment]
[GHA](https://github.com/neurogenomics/MAGMA_Celltyping/actions/runs/1497490713) indicates MAGMA isn't being installed on their machines with my current strategy. While I figure out a solution to this, here's some related changes I've made.

Before, if MAGMA wasn't installed, `MAGMA.Celltyping` would shut down and you could use any of it. I've changed this so that when you go to install the package, it will try to install it for you, but if it fails, you can still use the rest of the functions that don't depend on the MAGMA executable; including the `magma_install` function which can help guide users to finally install it successfully.

Of course this means some functions will throw errors if MAMGA isn't installed. Therefore i added to `magma_stop()` to the top of each function that relies on MAGMA, which checks if MAGMA is installed and gives an informative error message (as opposed to more cryptic errors):
```
Error in stopper("MAGMA must be installed to use this function.", msg) : 
  MAGMA must be installed to use this function. MAGMA_Celltyping was unable to install MAGMA.

Please download MAGMA manually from https://ctg.cncr.nl/software/magma
The executable should then be copied to /usr/local/bin

Alternatively, you can download it to wherever you want and add the folder containing it to your PATH.
That is, if you've placed the file in '~/Packages/'and you use bash (instead of e.g. zsh) then add to '~/.bash_profile' the following line:
'export PATH=~/Packages/magma:$PATH'
```

**Comment by bschilder** [comment]
Now passing on all OS.
