### ISSUE TITLE
Enable any species to be specified for the CTD & remove explicit checks or MGI/HGNC

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/MAGMA_Celltyping#50]

**Comment by bschilder** [comment]
Done!

Implemented using [`orthogene`](https://github.com/neurogenomics/orthogene) functions:
- [x] `celltype_associations_pipeline` and `prepare_quantile_groups`: CTD from any species are now automatically converted to humans genes, unless otherwise specified by user.
- [x] `map_specificity_to_entrez`: Cell-type-specific gene symbols are automatically converted to Entrez IDs (for compatibility with MAGMA).
- [x] `adjust_zstat_in_genesOut`: Uses `orthogene` to convert CTD.
- [x] `calculate_conditional_geneset_enrichment`
- [x] `calculate_celltype_associations`
- [x] `calculate_conditional_celltype_associations`
- [x] `calculate_conditional_celltype_enrichment_probabilities_wtLimma`

Related #57
